version: "3.9"

services:
  web:
    image: nginx:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    user: "1000:1000"
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.4.0
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "$DB_DATABASE"
      MYSQL_USER: "$DB_USERNAME"
      MYSQL_PASSWORD: "$DB_PASSWORD"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  app-network:
    driver: bridge
