<div class="container">
    <?php if (!empty($_SESSION['error'])): ?>
        <div class="alert alert-danger"><?= $_SESSION['error']; unset($_SESSION['error']); ?></div>
    <?php endif; ?>

    <form action="/login" method="POST" class="row justify-content-center">
        <div class="form-group mb-3 col-8">
            <label for="user_email" class="form-label">E-mail</label>
            <input id="user_email" type="email" name="user[email]" class="form-control" placeholder="Digite seu e-mail" required>
        </div>
        <div class="form-group mb-3 col-8">
            <label for="user_password" class="form-label">Senha</label>
            <input id="user_password" type="password" name="user[password]" class="form-control" placeholder="Digite sua senha" required>
        </div>
        <div class="col-8 text-end">
            <input type="submit" class="btn btn-secondary-custom" value="Entrar">
        </div>
    </form>
</div>
