<form action="<?= route('projects.update', ['id' => $project->getId()]) ?>" method="POST" class="<?= empty($project->hasErrors()) ? '' : 'was-validated' ?>" novalidate>
    <input type="hidden" name="_method" value="PUT">

    <div class="mb-3">
        <label for="project_title" class="form-label">Título:</label>
        <input type="text" name="project[title]" class="form-control" id="project_title" value="<?= $project->getTitle() ?>" required>
        <div class="invalid-feedback"><?= $project->errors('title') ? $project->errors('title') : '' ?></div>
    </div>

    <button type="submit" class="btn btn-primary">Atualizar</button>
</form>