<form action="update.php" method="POST" class="<?= empty($errors) ? '' : 'was-validated' ?>" novalidate>
    <input type="hidden" name="_method" value="PUT">
    <input type="hidden" name="project[id]" value="<?= $project['id'] ?>">
    <div class="mb-3">
        <label for="project_title" class="form-label">Título:</label>
        <input type="text" name="project[title]" class="form-control" id="project_title" value="<?= $project['title'] ?>" required>
        <div class="invalid-feedback"><?= isset($errors['title']) ? $errors['title'] : '' ?></div>
    </div>

    <button type="submit" class="btn btn-primary">Registrar</button>
</form>