<form action="<?= route('projects.create') ?>" method="POST" class="<?= $project->hasErrors() ? 'was-validated' : '' ?>" novalidate>
    <div class="mb-3">
        <label for="project_title" class="form-label">Título:</label>
        <input type="text"
               name="project[title]"
               class="form-control <?= $project->errors('title') ? 'is-invalid' : '' ?>"
               id="project_title"
               value="<?= htmlspecialchars($project->title) ?>"
               required>

        <?php if ($project->errors('title')) : ?>
            <div class="invalid-feedback">
                <?= htmlspecialchars($project->errors('title')) ?>
            </div>
        <?php endif; ?>
    </div>

    <button type="submit" class="btn btn-primary">Registrar</button>
</form>