name: Continous Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Start services
        run: ./run up -d

      # --- ALTERAÇÃO APLICADA ---
      # Adiciona uma pausa para garantir que o DB esteja pronto
      - name: Wait for database
        run: sleep 15

      - name: PHPUnit
        run: ./run test

  code_quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env

      - name: Composer install
        run: ./run composer install

      - name: Start services
        run: ./run up -d

      # --- ALTERAÇÃO APLICADA ---
      # Adiciona uma pausa aqui também por segurança
      - name: Wait for database
        run: sleep 15

      - name: PSR-4 Checker
        run: ./run composer dump-autoload --optimize --strict-psr

      - name: PHPCS
        run: ./run phpcs

      - name: PHPStan
        run: ./run phpstan
