<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?? 'Login' ?></title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <main class="d-flex justify-content-center align-items-center vh-100">
        <div class="card shadow-lg p-4 w-50">
            <h2 class="text-center mb-4"><?= $title ?? 'Login' ?></h2>
            <?php require __DIR__ . '/../authentications/new.phtml'; ?>
        </div>
    </main>
</body>
</html>
